version: '3.1'
services:
  nginx:
    container_name: laravel_nginx
    image: nginx:latest
    volumes:
     - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./src:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    ports:
      - 80:80
    links:
      - php:laravel_php
    depends_on:
      - php

  php:
    container_name: laravel_php
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile
    image: lima195/php-fpm7.4:lastest
    user: john
    volumes:
     - ./src:/usr/share/nginx/www
     - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /usr/share/nginx/www

  db:
    container_name: laravel_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app

  adminer:
    container_name: laravel_adminer
    image: adminer
    ports:
      - 8080:8080
    links:
      - db

  mailhog:
    container_name: laravel_mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
